sudo: false

language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

matrix:
  allow_failures:
    python: "3.6-dev"
    python: "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run -m unittest -vb tests

after_sucess:
  - coverage report -m
  - pip install codecov && codecov
